name: Generate RSS Jadwal Sholat Surabaya

on:
  schedule:
    - cron: '0 18 * * *' # Menjalankan setiap jam 1 pagi (GMT+7)

jobs:
  generate-rss-surabaya:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run PHP Script and Generate RSS
      run: 
        php prayer-times-surabaya.php > output/prayer_times_surabaya.xml

    - name: Commit and Push Changes
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add output/prayer_times_surabaya.xml
          git commit -m "Update Jadwal Sholat Surabaya RSS file"
          git push
